### ISSUE TITLE
Profiles and Templates share a name pool?

### ISSUE THREAD

**Issue by Jonxslays** [nusex/nusex#38]
### Steps to reproduce

1. Install nusex.
2. Run `nusex profile -n test`.
3. Complete the prompts.
4. Attempt to build a new Template with `nusex build test`.
5. The following error is produced:
> 💥 A profile is already using that name.

### Expected behaviour

Profiles and Templates should use different name pools so that if the user wanted they could have both a Profile and Template with the same name. I know this would require some reworking like with the `delete` subcommand, but I feel like it is a useful adjustment. 

### Current behaviour

The Template fails to create due to the Profile with the same name. 

### System information

nusex 1.2.4.post1
CPython 3.10.0 GCC 11.1.0
Linux 5.10.83-1-lts
└──Arch Linux

### Checklist

- [X] I have searched the issue tracker for duplicate issues and couldn't find any. If this is a follow-up issue, I have specified as such.

**Comment by parafoxia** [comment]
This is actually intentional to provide a slicker interface for certain commands, like the delete command as you say. It's sort of the same idea as Git having branches and tags use the same namespace, so you can just push them up with less faff.

I could maybe look at splitting these but I'm not 100% sure it'd be worth it.
